# 数据库
HOSTNAME = ''
PORT = '3306'
DATABASE = ''
USERNAME = ''
PASSWORD = ''
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)

JSON_AS_ASCII = False
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_DATABASE_URI = DB_URI

SECRET_KEY = 'jbwkbjevkanvejk352663335515'

# MAX_CONTENT_LENGTH = 16 * 1024 * 1024
