"""empty message

Revision ID: c7a851c91209
Revises: b41c920adbd5
Create Date: 2022-07-26 21:57:52.129366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a851c91209'
down_revision = 'b41c920adbd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('big_data', sa.Column('size', sa.String(length=45), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('big_data', 'size')
    # ### end Alembic commands ###
