"""empty message

Revision ID: e9886add43e1
Revises: c7a851c91209
Create Date: 2022-07-27 10:20:41.848946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9886add43e1'
down_revision = 'c7a851c91209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('appendix_name', sa.String(length=45), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'appendix_name')
    # ### end Alembic commands ###
